# Generated by Django 3.1.7 on 2021-03-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='direc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='firm',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Ruta Firma'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='office',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Oficina'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='telephone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Extencion'),
        ),
        migrations.AddField(
            model_name='user',
            name='direc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='user',
            name='firm',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Ruta Firma'),
        ),
        migrations.AddField(
            model_name='user',
            name='office',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Oficina'),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Extencion'),
        ),
    ]
