# Generated by Django 3.0.6 on 2021-04-02 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tipo_asistencia', '0001_initial'),
        ('tema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenciaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='Fecha')),
                ('nombre_apellidos_contacto', models.TextField(max_length=150, unique=True, verbose_name='Nombres Apellidos de contacto')),
                ('datos_contacto', models.TextField(max_length=150, unique=True, verbose_name='Datos del Contacto')),
                ('acciones', models.CharField(max_length=150, unique=True, verbose_name='Acciones')),
                ('compromisos', models.CharField(max_length=150, unique=True, verbose_name='Compromisos')),
                ('firma', models.CharField(blank=True, max_length=150, null=True, verbose_name='Firma')),
                ('is_active', models.BooleanField(default=True)),
                ('fk_tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tema.TemaModel')),
                ('fk_tipo_asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo_asistencia.TipoAsistenciaModel')),
                ('fk_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
