# Generated by Django 3.2.2 on 2021-05-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_asistencia', '0002_auto_20210413_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciamodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
